name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update ke versi terbaru

    - name: Set up Python
      uses: actions/setup-python@v5  # Update ke versi terbaru
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask App (Optional)
      run: |
        python -m flask run --host=0.0.0.0 --port=5000 &
        sleep 10
        curl http://localhost:5000
